Update build-custom.yml

diff --git a/.github/workflows/build-custom.yml b/.github/workflows/build-custom.yml
--- a/.github/workflows/build-custom.yml
+++ b/.github/workflows/build-custom.yml
@@ -36,34 +36,56 @@ jobs:
 
       - name: Add custom plugins
         run: |
-          cd src
-          mkdir -p userplugins
-          cd userplugins
+          rm -rf src/userplugins/* || true
+          mkdir -p src/userplugins
+          cd src/userplugins
           git init
           git remote add origin https://github.com/NatsukashiiOwU/vencord_goofy_plugins.git
           git config core.sparseCheckout true
           echo "bulkRoles/" >> .git/info/sparse-checkout
           echo "extractChannelMessages/" >> .git/info/sparse-checkout
-          git pull origin main
+          git pull origin main --depth=1 || { echo "Failed to pull plugins"; exit 1; }
           cd ../..
+        continue-on-error: false
 
-      - name: Build Vencord
-        run: pnpm build
+      - name: Build
+        run: pnpm build --standalone
 
-      - name: Package builds
+      - name: Clean up obsolete files
         run: |
-          pnpm package
-          pnpm package:dir
+            rm -rf dist/*-unpacked dist/vendor Vencord.user.css vencordDesktopRenderer.css vencordDesktopRenderer.css.map
 
-      - name: Create Release
-        uses: softprops/action-gh-release@v1
-        with:
-          tag_name: "custom-${{ github.sha }}"
-          name: "Custom Vencord Build ${{ github.sha }}"
-          files: |
-            dist/*.asar
-            dist/*.zip
-            dist/*.js
-            dist/*.css
+      - name: Get some values needed for the release
+        id: release_values
+        run: |
+            echo "release_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+
+      - name: Upload DevBuild as release
+        if: github.repository == 'NatsukashiiOwU/Vencord'
+        run: |
+           gh release upload devbuild --clobber dist/*
+           gh release edit devbuild --title "DevBuild $RELEASE_TAG"
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+           RELEASE_TAG: ${{ env.release_tag }}
+
+      - name: Upload DevBuild to builds repo
+        if: github.repository == 'Vendicated/Vencord'
+        run: |
+           git config --global user.name "$USERNAME"
+           git config --global user.email actions@github.com
+
+           git clone https://$USERNAME:$API_TOKEN@github.com/$GH_REPO.git upload
+           cd upload
+
+           GLOBIGNORE=.git:.gitignore:README.md:LICENSE
+           rm -rf *
+           cp -r ../dist/* .
+
+           git add -A
+           git commit -m "Builds for https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
+           git push --force https://$USERNAME:$API_TOKEN@github.com/$GH_REPO.git
+        env:
+           API_TOKEN: ${{ secrets.BUILDS_TOKEN }}
+           GH_REPO: Vencord/builds
+           USERNAME: GitHub-Actions
